<div id="navMenuUser">
    <h1>&nbsp; &nbsp; ≡ USER</h1>
    <li class="menu"> <!-- costituisce ogni sezione del menu principale -->
        <ul>
            <!-- titolo della sezione che fa aprire il sotto menu -->
            <li class="title"><a href="#">&nbsp; &nbsp; gestione profilo</a></li>
            <li class="sub-menu">
                <ul>
                    <li>modifica profilo</li>                   
                </ul>
            </li>
        </ul> 
    </li> 
</div>