<div id="content">	
    <!-- SUBHEADER CONTENTENTE INFORMAZIONIA AGGIUNTIVE AL SITO -->
    <div id="subheader">
        &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
        <a href=""><img src="<?php echo $this->baseURL();?>/images/icons/h24.png" class="icons"></img><h4>offerte aggiornate 24 ore su 24 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</h4></a>
        <a href=""><img src="<?php echo $this->baseURL();?>/images/icons/brands.png" class="icons"></img><h4>i migliori brands a portata di click &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</h4></a>
        <a href=""><img src="<?php echo $this->baseURL();?>/images/icons/risparmio.png" class="icons"></img><h4>risparmio garantito &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</h4></a>
        <a href="<?= $this->url(array('controller'=>'public','action'=>'viewstatic','staticPage' => 'faq','default',true));?>"><img src="<?php echo $this->baseURL();?>/images/icons/FAQ.png" class="icons"></img><h4>dubbi? FAQ semplice e intuitiva!</h4></a>
    </div>	
    <div id="navMenu">
        <ul id="categorie">
            <h1>&nbsp; &nbsp; ≡ CATEGORIE</h1>
            <!-- lista delle categorie dei prodotti presenti nel sito -->
            <?php foreach ($this->tipologie as $tipologia) :?>
            <li><a href="<?= $this->url(array('controller'=>'public','action'=>'categorie','catId'=>$tipologia->nometipologia,'default',true));?>">&nbsp; &nbsp;<?php echo $tipologia->nometipologia ?></a></li>
            <?php endforeach;?>
        </ul>
    </div>
     <?php echo '<h1 class="titolocategoria">Filtra '.$this->categoria.'per '.$this->nomecercato.'</h1>'; ?>
     <?php foreach ($this->offertaPerCategoria as $offertaCategoria) :?>
		<div id="offertaCategoria">
                     <?php echo $this->offertaImg($offertaCategoria->immagine,array('class' => 'immagineOfferta'));?>
			<div id="infoOfferta"> 
                               
                                <?php echo '<h5>'. $offertaCategoria->nomeprodotto.'</h5>'?>
				<br>
                                <?php echo '<h6>'. $offertaCategoria->localita.'</h6>'?>
                                <br>
                                <a href="<?= $this->url(array('controller'=>'public','action'=>'viewstatic','staticPage' => 'profilobrands','default',true));?>">
                                <?php echo '<h7>'. $offertaCategoria->nome.'</h7>'?></a>
				<br>

				<?php echo '<h8>'. $offertaCategoria->tipo.'</h8>'?>
>
				<br>
                                <?php echo '<h8>dal '.'<b>'.$offertaCategoria->datainizio.'</b> al <b>'.
                                        $offertaCategoria->datafine.'</b>'.'</h8>'?>
				<button id="stampaofferta"></button>
                                <a href="<?= $this->url(array('controller'=>'public','action'=>'viewstatic','staticPage' => 'informazioneofferta','default',true));?>"><button id="visualizzaofferta"></button></a>
			</div>
		</div>
                <?php endforeach ?>
          <?php if($this->offertaPerCategoria instanceof Zend_Paginator) {
                echo $this->paginationControl($this->offertaPerCategoria,'Sliding','public/_paginatorCategorieFiltrate.phtml');
	  } 
	  ?>

</div>