<div id="content">	
    <div id="navMenu">
    </div>
    <?php echo '<h1 class="titolocategoria">Offerte'.$this->tipoofferta.' per la tipologia: '.$this->nomecercato.' </h1>';?>
    <div id="filtracategoria">
    <?php foreach ($this->offerte as $offerta) :?>
		<div id="offertaCategoria">
                     <?php echo $this->offertaImg($offerta->immagine,array('class' => 'immagineOfferta'));?>
			<div id="infoOfferta"> 
                               
                                <?php echo '<h5>'. $offerta->nomeprodotto.'</h5>'?>
				<br>
                                <?php echo '<h6>'. $offerta->localita.'</h6>'?>
                                <br>
                     <a href="<?= $this->url(array('controller'=>'public','action'=>'profilobrands','nomeazienda' => $offerta->nome,'default',true));?>">
                                   
                           <?php echo '<h7>'. $offerta->nome.'</h7>'?></a>
				<br>

				<?php echo '<h8>'. $offerta->tipo.'</h8>'?>

				<br>
                                <?php echo '<h8>dal '.'<b>'.$offerta->datainizio.'</b> al <b>'.
                                        $offerta->datafine.'</b>'.'</h8>'?>
				<button id="stampaofferta" onClick="<?php 
                    if($this->authInfo('role')=='user'){
                       $indirizzo = "window.location.href='".$this->url(array('controller'=>'user','action'=>'stampaofferta','offertaid' => $offerta->idpromozione ,'default',true))."'"; 
                      echo $indirizzo;
                    }
                    else
                        echo 'myFunction()';?>"></button>
                                <a href="<?= $this->url(array('controller'=>'public','action'=>'informazioneofferta','offertaid'=>$offerta->idpromozione,'default',true));?>"><button id="visualizzaofferta"></button></a>
			
                        <div id="snackbar">Per accedere al codice coupon della promozione occorre registrarsi come utente!</div>
			</div>
		</div>
                <?php endforeach ?>
          <?php if($this->offerte instanceof Zend_Paginator) {
                echo $this->paginationControl($this->offerte,'Sliding','public/paginator/_paginatorFiltraTipologia.phtml');
	  } 
	  ?>
    </div>
    
</div>
