<div id="content">	
    <!-- SUBHEADER CONTENTENTE INFORMAZIONIA AGGIUNTIVE AL SITO -->
    <div id="subheader">
        &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
        <a onClick="myFunctionThree()"><img src="<?php echo $this->baseURL();?>/images/icons/h24.png" class="icons"></img><h4>offerte aggiornate 24 ore su 24 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</h4></a>
        
        <div id="snackbartwo">
        il Team di Coupon World si assicura di non lasciare i propri clienti privi di offerte e per questo motivo il sito è sempre aggiornato.
        Visitalo ogni giorno!
        </div>
        
        <div id="snackbarthree">
        secondo recenti statistiche fare shopping con l'utilizzo dei coupon riduce il costo complessivo pro capite fino ad un totale di 25% !
        </div>
        
        
        <a href="<?= $this->url(array('controller'=>'public','action'=>'paginadeibrands','default',true));?>"><img src="<?php echo $this->baseURL();?>/images/icons/brands.png" class="icons"></img><h4>clicca qui per vedere tutti i brands! &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</h4></a>
        <a onClick="myFunctionFour()"><img src="<?php echo $this->baseURL();?>/images/icons/risparmio.png" class="icons"></img><h4>risparmio garantito &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</h4></a>
        <a href="<?= $this->url(array('controller'=>'public','action'=>'paginafaq','default',true));?>"><img src="<?php echo $this->baseURL();?>/images/icons/FAQ.png" class="icons"></img><h4>dubbi? FAQ semplice e intuitiva!</h4></a>
       
    </div>	
    <div id="navMenu">
        <ul id="categorie">
            <h1>&nbsp; &nbsp; ≡ TIPOLOGIE</h1>
            <!-- lista delle categorie dei prodotti presenti nel sito -->
            <?php foreach ($this->tipologie as $tipologia) :?>
            <li><a href="<?= $this->url(array('controller'=>'public','action'=>'categorie','catId'=>$tipologia->nometipologia,'default',true));?>">&nbsp; &nbsp;<?php echo $tipologia->nometipologia ?></a></li>
            <?php endforeach;?>
        </ul>
    </div>
    <!-- Sezione che contiene lo slideshow e i promotion banner (che diventa poi dinamica al click sulle categorie) -->
    
    <!-- SLIDESHOW CHE CONTIENE I BANNER DELLE CATEGORIE -->
    <div class="slideshow-container">
        <div class="mySlides fade">
            <img src="<?php echo $this->baseURL();?>/images/banners/technology_banner.jpg" style="width:100%">
            </a>
        </div>
        
        <div class="mySlides fade">
            <img src="<?php echo $this->baseURL();?>/images/banners/office_banner.jpg" style="width:100%">
            </a>
        </div>
        
        <div class="mySlides fade">
            <img src="<?php echo $this->baseURL();?>/images/banners/clothes_banner.jpg" style="width:100%">
            </a>
        </div>
        
        <div class="mySlides fade">
            <img src="<?php echo $this->baseURL();?>/images/banners/food_banner.jpg" style="width:100%">
            </a>
        </div>
        
        <div class="mySlides fade">
            <img src="<?php echo $this->baseURL();?>/images/banners/enternaiment_banner.jpg" style="width:100%">
            </a>
        </div>
        
        <div class="mySlides fade">
            <img src="<?php echo $this->baseURL();?>/images/banners/sportandfitness_banner.jpg" style="width:100%">
            </a>
        </div>
        
        <div class="mySlides fade">
            <img src="<?php echo $this->baseURL();?>/images/banners/homeandgarden_banner.jpg" style="width:100%">
            </a>
        </div>
        
        <div class="mySlides fade">
            <img src="<?php echo $this->baseURL();?>/images/banners/health_banner.jpg" style="width:100%">
            </a>
        </div>
        
        <div class="mySlides fade">
            <img src="<?php echo $this->baseURL();?>/images/banners/travel_banner.jpg" style="width:100%">
            </a>
        </div>
        
        <div class="mySlides fade">
            <img src="<?php echo $this->baseURL();?>/images/banners/carandmoto_banner.jpg" style="width:100%">
            </a>
        </div>
        
        <div class="mySlides fade">
            <img src="<?php echo $this->baseURL();?>/images/banners/animals_banner.jpg" style="width:100%">
            </a>
        </div>
    </div>
    <!-- SCRIPT CHE PERMETTE LA VISUALIZZAZIONE DELLO SLIDESHOW -->
    <script type="text/javascript">
        var slideIndex = 0;
        showSlides();
        function showSlides() {
            var i;
            var slides = document.getElementsByClassName("mySlides");
            for (i = 0; i < slides.length; i++) {
                slides[i].style.display = "none"; 
            }
            slideIndex++;
            if (slideIndex> slides.length) {slideIndex = 1} 
            slides[slideIndex-1].style.display = "block"; 
            setTimeout(showSlides, 3500); // Change image every 3.5 seconds
        }
    </script> 
    <!-- due container che contengono banner pubblicitari -->
    <div id="promotion_banner_one">
        <h2>ALL FOR HIM</h2>
    </div>
    <br>
    <div id="promotion_banner_two">
        <h2>ALL FOR HER</h2>
    </div>
    <!-- div che contiene un banner con foto, posizionato sul banner -->
    <div id="upfooter"></div>
    <br>
     <div id="snackbar">Per accedere al codice coupon della promozione occorre registrarsi come utente!</div>
    <div id="offerteInScadenza">
        <h1>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ❕ OFFERTE IN SCADENZA ❕</h1>
        <div class="espandi3"><span>FILTRA PER AZIENDA +</span></div>
        <div class="filtraForm3">
            <?php echo $this->filtraAziendaFormS ?>
        </div>
        <div class="espandi4"><span>FILTRA PER TIPOLOGIA +</span></div>
        <div class="filtraForm4">
            <?php echo $this->filtraTipologiaFormS ?>   
        </div>

        <?php foreach ($this->offerteInScadenza as $offertaInScadenza) :?>
        <div id="offerta">
            <?php echo $this->offertaImg($offertaInScadenza->immagine,array('class' => 'immagineOfferta'));?>
            <div id="infoOfferta"> 
                <?php echo '<h5>'. $offertaInScadenza->nomeprodotto.'</h5>'?>                
                
                <br>
                    <?php echo '<h6>'. $offertaInScadenza->tipo.'</h6>'?>
                <br>
                <a href="<?= $this->url(array('controller'=>'public','action'=>'profilobrands','nomeazienda' => $offertaInScadenza->nome,'default',true));?>">
				<?php echo '<h9>'. $offertaInScadenza->nome.'</h9>'?></a>
                    <br>
                                <?php echo '<h7>'. $offertaInScadenza->nometipologia.'</h7>'?>
                    <br>
                                <?php echo '<h8>dal '.'<b>'.$offertaInScadenza->datainizio.'</b> al <b>'.
                                        $offertaInScadenza->datafine.'</b>'.'</h8>'?>
                                            
                                            
                    <button id="stampaofferta2" onClick="<?php 
                    
                 
                    
                    if($this->authInfo('role')=='user'){


                       $indirizzo = "window.location.href='".$this->url(array('controller'=>'user','action'=>'stampaofferta','offertaid' => $offertaInScadenza->idpromozione ,'default',true))."'"; 

                      echo $indirizzo;
                    }
                    else
                        echo 'myFunction()';?>"></button>
                    
            
                    <a href="<?php echo $this->url(array('controller'=>'public','action'=>'informazioneofferta','offertaid' => $offertaInScadenza->idpromozione ,'default',true));?>"><button id="visualizzaofferta2"></button></a>
            </div>
        </div>
        
        
        
                <?php endforeach ?>
        <div id="paginatorOfferteScadenza">
                <?php if($this->offerteInScadenza instanceof Zend_Paginator) {
	  		echo $this->paginationControl($this->offerteInScadenza,'Sliding','public/paginator/_paginatorOffertaInScadenza.phtml');
                   } 
                 ?>
        </div>
    </div>
</div>
