<div id="content">	
	<!-- SUBHEADER CONTENTENTE INFORMAZIONIA AGGIUNTIVE AL SITO -->
	<div id="subheader">
		&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
		<a href=""><img src="<?php echo $this->baseURL();?>/images/icons/h24.png" class="icons"></img><h4>offerte aggiornate 24 ore su 24 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</h4></a>
		<a href=""><img src="<?php echo $this->baseURL();?>/images/icons/brands.png" class="icons"></img><h4>i migliori brands a portata di click &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</h4></a>
		<a href=""><img src="<?php echo $this->baseURL();?>/images/icons/risparmio.png" class="icons"></img><h4>risparmio garantito &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</h4></a>
		<a href="<?= $this->url(array('controller'=>'public','action'=>'viewstatic','staticPage' => 'faq','default',true));?>"><img src="<?php echo $this->baseURL();?>/images/icons/FAQ.png" class="icons"></img><h4>dubbi? FAQ semplice e intuitiva!</h4></a>
	</div>	
	<div id="navMenu">
            <ul id="categorie">
            <h1>&nbsp; &nbsp; ≡ CATEGORIE</h1>
            <!-- lista delle categorie dei prodotti presenti nel sito -->
            <li><a href="<?= $this->url(array('controller'=>'public','action'=>'categorie','catId'=>'tecnologia','default',true));?>">&nbsp; &nbsp; Tecnologia</a></li>
            <li><a href="<?= $this->url(array('controller'=>'public','action'=>'categorie','catId'=>'ufficioeservizi','default',true));?>">&nbsp; &nbsp; Ufficio e servizi</a></li>
            <li><a href="<?= $this->url(array('controller'=>'public','action'=>'categorie','catId'=>'modaeabbigliamento','default',true));?>">&nbsp; &nbsp; Moda e abbigliamento</a></li>
            <li><a href="<?= $this->url(array('controller'=>'public','action'=>'categorie','catId'=>'cibiebevande','default',true));?>">&nbsp; &nbsp; Cibi e bevande</a></li>
            <li><a href="<?= $this->url(array('controller'=>'public','action'=>'categorie','catId'=>'giochiedintrattenimento','default',true));?>">&nbsp; &nbsp; Giochi ed intrattenimento</a></li>
            <li><a href="<?= $this->url(array('controller'=>'public','action'=>'categorie','catId'=>'sportefitness','default',true));?>">&nbsp; &nbsp; Sport e fitness</a></li>
            <li><a href="<?= $this->url(array('controller'=>'public','action'=>'categorie','catId'=>'casaegiardino','default',true));?>">&nbsp; &nbsp; Casa e giardino</a></li>
            <li><a href="<?= $this->url(array('controller'=>'public','action'=>'categorie','catId'=>'saluteebellezza','default',true));?>">&nbsp; &nbsp; Salute e bellezza</a></li>
            <li><a href="<?= $this->url(array('controller'=>'public','action'=>'categorie','catId'=>'viaggi','default',true));?>">&nbsp; &nbsp; Viaggi</a></li>
            <li><a href="<?= $this->url(array('controller'=>'public','action'=>'categorie','catId'=>'autoemoto','default',true));?>">&nbsp; &nbsp; Auto e moto</a></li>
            <li><a href="<?= $this->url(array('controller'=>'public','action'=>'categorie','catId'=>'animali','default',true));?>">&nbsp; &nbsp; Animali</a></li>
            </ul>
	</div>
	<div id="campoCercaAzienda">
		<h2>&nbsp; &nbsp;BRANDS</h2>
		<input type="text" name="search" placeholder="Cerca l'offerta per azienda">
		<button></button>
	</div>	
	<!-- Sezione che contiene lo slideshow e i promotion banner (che diventa poi dinamica al click sulle categorie) -->

		<!-- SLIDESHOW CHE CONTIENE I BANNER DELLE CATEGORIE -->
  <div class="slideshow-container">
  			<div class="mySlides fade">
                        <a href="<?= $this->url(array('controller'=>'public','action'=>'categorie','catId'=>'tecnologia','default',true));?>">
    			<img src="<?php echo $this->baseURL();?>/images/banners/technology_banner.jpg" style="width:100%">
                        </a>
  			</div>

  			<div class="mySlides fade">
                            <a href="<?= $this->url(array('controller'=>'public','action'=>'categorie','catId'=>'ufficioeservizi','default',true));?>">
                            <img src="<?php echo $this->baseURL();?>/images/banners/office_banner.jpg" style="width:100%">
                            </a>
  			</div>

  			<div class="mySlides fade">
                            <a href="<?= $this->url(array('controller'=>'public','action'=>'categorie','catId'=>'modaeabbigliamento','default',true));?>">
                            <img src="<?php echo $this->baseURL();?>/images/banners/clothes_banner.jpg" style="width:100%">
                            </a>
  			</div>
  
  			<div class="mySlides fade">
                            <a href="<?= $this->url(array('controller'=>'public','action'=>'categorie','catId'=>'ciboebevande','default',true));?>">
                            <img src="<?php echo $this->baseURL();?>/images/banners/food_banner.jpg" style="width:100%">
                            </a>
 			</div>
  
  			<div class="mySlides fade">
                            <a href="<?= $this->url(array('controller'=>'public','action'=>'categorie','catId'=>'giochieintrattenimento','default',true));?>">
                            <img src="<?php echo $this->baseURL();?>/images/banners/enternaiment_banner.jpg" style="width:100%">
                            </a>
  			</div>
  
  			<div class="mySlides fade">
                            <a href="<?= $this->url(array('controller'=>'public','action'=>'categorie','catId'=>'sportefitness','default',true));?>">
                            <img src="<?php echo $this->baseURL();?>/images/banners/sportandfitness_banner.jpg" style="width:100%">
                            </a>
  			</div>
  
  			<div class="mySlides fade">
                            <a href="<?= $this->url(array('controller'=>'public','action'=>'categorie','catId'=>'casaegiardino','default',true));?>">
                            <img src="<?php echo $this->baseURL();?>/images/banners/homeandgarden_banner.jpg" style="width:100%">
                            </a>
  			</div>
  
  			<div class="mySlides fade">
                            <a href=".<?= $this->url(array('controller'=>'public','action'=>'categorie','catId'=>'saluteebellezza','default',true));?>">
                            <img src="<?php echo $this->baseURL();?>/images/banners/health_banner.jpg" style="width:100%">
                            </a>
  			</div>
  
  			<div class="mySlides fade">
                            <a href="<?= $this->url(array('controller'=>'public','action'=>'categorie','catId'=>'viaggi','default',true));?>">
                            <img src="<?php echo $this->baseURL();?>/images/banners/travel_banner.jpg" style="width:100%">
                            </a>
  			</div>
  
  			<div class="mySlides fade">
                            <a href="<?= $this->url(array('controller'=>'public','action'=>'categorie','catId'=>'autoemoto','default',true));?>">
                            <img src="<?php echo $this->baseURL();?>/images/banners/carandmoto_banner.jpg" style="width:100%">
                            </a>
  			</div>
  
  			<div class="mySlides fade">
                            <a href="<?= $this->url(array('controller'=>'public','action'=>'categorie','catId'=>'animali','default',true));?>">
                            <img src="<?php echo $this->baseURL();?>/images/banners/animals_banner.jpg" style="width:100%">
                            </a>
  			</div>
		</div>
		<!-- SCRIPT CHE PERMETTE LA VISUALIZZAZIONE DELLO SLIDESHOW -->
		<script type="text/javascript">
			var slideIndex = 0;
			showSlides();
			function showSlides() {
    		var i;
    		var slides = document.getElementsByClassName("mySlides");
    		for (i = 0; i < slides.length; i++) {
        		slides[i].style.display = "none"; 
    			}
			slideIndex++;
    		if (slideIndex> slides.length) {slideIndex = 1} 
				slides[slideIndex-1].style.display = "block"; 
    			setTimeout(showSlides, 3500); // Change image every 3.5 seconds
			}
		</script> 
		<!-- due container che contengono banner pubblicitari -->
		<div id="promotion_banner_one">
			<h2>ALL FOR HIM</h2>
		</div>
		<br>
		<div id="promotion_banner_two">
			<h2>ALL FOR HER</h2>
		</div>
          


	<!-- div che contiene un banner con foto, posizionato sul banner -->
	<div id="upfooter"></div>
	<div id="offerteDelGiorno">
		<h1>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;☆ OFFERTE DEL GIORNO ☆</h1>
                <?php foreach ($this->offerteDelGiorno as $offertaDelGiorno) :?>
		<div id="offerta">
			<div id="infoOfferta"> 
                                <?php echo '<h5>'. $offertaDelGiorno->nomeprodotto.'</h5>'?>
                                <br>
				<?php echo '<h6>'. $offertaDelGiorno->categoria.'</h6>'?>
				<br>
				<?php echo '<h7>'. $offertaDelGiorno->azienda_idazienda.'</h7>'?>
				<br>
				<?php echo '<h8>'. $offertaDelGiorno->azienda_idazienda.'</h8>'?>
				<br>
                                <?php echo '<h8>dal '.'<b>'.$offertaDelGiorno->datainizio.'</b> al <b>'.
                                        $offertaDelGiorno->datafine.'</b>'.'</h8>'?>
				<button id="stampaofferta"></button>
			</div>
		</div>
                <?php endforeach ?>
            
          <!--paginazione  -->
	  <?php if($this->offerta instanceof Zend_Paginator) {
                echo $this->paginationControl($this->offerta,'Sliding','public/_paginatorOfferteDelGiorno.phtml');
	  } 
	  ?>
              </div>
        <br>
	<br>
	<br>
	<br>
	<br>
	<div id="offerteInScadenza">
		<h1>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ❕ OFFERTE IN SCADENZA ❕</h1>
                <?php foreach ($this->offerteInScadenza as $offertaInScadenza) :?>
		<div id="offerta">
			<div id="infoOfferta"> 
                                <?php echo '<h5>'. $offertaInScadenza->nomeprodotto.'</h5>'?>
                                <br>
				<?php echo '<h6>'. $offertaInScadenza->categoria.'</h6>'?>
				<br>
				<?php echo '<h7>'. $offertaInScadenza->azienda_idazienda.'</h7>'?>
				<br>
				<?php echo '<h8>'. $offertaInScadenza->azienda_idazienda.'</h8>'?>
				<br>
                                <?php echo '<h8>dal '.'<b>'.$offertaInScadenza->datainizio.'</b> al <b>'.
                                        $offertaInScadenza->datafine.'</b>'.'</h8>'?>
				<button id="stampaofferta"></button>
			</div>
		</div>
                <?php endforeach ?>
                <?php if($this->offerta instanceof Zend_Paginator) {
	  		echo $this->paginationControl($this->offerta,'Sliding','public/_paginatorInScadenza.phtml');
                   } 
                 ?>
	</div>
</div>
