<!doctype html>
<html lang="it-IT">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Welcome</title>
<link href="css/welcome.css" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Titillium+Web" rel="stylesheet">
</head>
<body>

<!-- contenitore principale della pagina -->
<div class="main_container"> 
 
  <!-- barra contenente il logo -->
  <header> 
  	<img srcset="images/LogoCW.png" width="300" height="100">
  </header>
  
  <!-- sezione del banner  -->
  <section class="banner" id="banner">
   <div class="container_message_onboard">
    <h2 class="message_onbanner">UN MODO DIVERSO DI FARE SHOPPING <br>CON IL RISPARMIO A PORTATA DI CLICK</br></h2>
   </div>
   <button onClick="window.location.href='<?=
    /*Reindirizzo all'azione index del controller Public*/
    $this->url(array('controller'=>'public','action'=>'home','default',true));
    ?>';" class="button_enter">SCOPRI DI PIÚ</button>
  </section>
  
  <!-- sezione dei brands  -->
  <section class="brands" id="brands">
  	<h1 class="title_messages">TOP BRANDS</h1>
  	<h2 class="subtitle_messages">Oltre centomila aziende leader in italia e all'estero. Risparmiare non é mai stato cosi semplice grazie al supporto dei migliori brands.</h2>
  	<ul id="griglia_brands">
		
                <li><img title="clicca qui per vedere le loro offerte" onclick="window.location.href='<?= $this->url(array('controller'=>'public','action'=>'profilobrands','nomeazienda' => 'Adidas','default',true));?>';" src="images/list brands/b1.png" width="100" height="100"></img> </li>
   		<li><img title="clicca qui per vedere le loro offerte" onclick="window.location.href='<?= $this->url(array('controller'=>'public','action'=>'profilobrands','nomeazienda' => 'Sony','default',true));?>';" src="images/list brands/b2.png" width="100" height="100"></img></li>
   		<li><img title="clicca qui per vedere le loro offerte" onclick="window.location.href='<?= $this->url(array('controller'=>'public','action'=>'profilobrands','nomeazienda' => 'Colgate','default',true));?>';" src="images/list brands/b3.png" width="100" height="100"></img></li>
   		<li><img title="clicca qui per vedere le loro offerte" onclick="window.location.href='<?= $this->url(array('controller'=>'public','action'=>'profilobrands','nomeazienda' => 'Nestle','default',true));?>';" src="images/list brands/b4.png" width="100" height="100"></img></li>
   		<li><img title="clicca qui per vedere le loro offerte" onclick="window.location.href='<?= $this->url(array('controller'=>'public','action'=>'profilobrands','nomeazienda' => 'Loreal','default',true));?>';" src="images/list brands/b5.png" width="100" height="100"></img></li>
   		<li><img title="clicca qui per vedere le loro offerte" onclick="window.location.href='<?= $this->url(array('controller'=>'public','action'=>'profilobrands','nomeazienda' => 'Danone','default',true));?>';" src="images/list brands/b6.png" width="100" height="100"></img></li>
   		<li><img title="clicca qui per vedere le loro offerte" onclick="window.location.href='<?= $this->url(array('controller'=>'public','action'=>'profilobrands','nomeazienda' => 'Gucci','default',true));?>';" src="images/list brands/b7.png" width="100" height="100"></img></li>
   		<li><img title="clicca qui per vedere le loro offerte" onclick="window.location.href='<?= $this->url(array('controller'=>'public','action'=>'profilobrands','nomeazienda' => 'Hp','default',true));?>';" src="images/list brands/b8.png" width="100" height="100"></img></li>
   		<li><img title="clicca qui per vedere le loro offerte" onclick="window.location.href='<?= $this->url(array('controller'=>'public','action'=>'profilobrands','nomeazienda' => 'Canon','default',true));?>';" src="images/list brands/b9.png" width="100" height="100"></img></li>
   		<li><img title="clicca qui per vedere le loro offerte" onclick="window.location.href='<?= $this->url(array('controller'=>'public','action'=>'profilobrands','nomeazienda' => 'Kellogs','default',true));?>';" src="images/list brands/b10.png" width="100" height="100"></img></li>
   		<li><img title="clicca qui per vedere le loro offerte" onclick="window.location.href='<?= $this->url(array('controller'=>'public','action'=>'profilobrands','nomeazienda' => 'Nescafe','default',true));?>';" src="images/list brands/b11.png" width="100" height="100"></img></li>
   		<li><img title="clicca qui per vedere le loro offerte" onclick="window.location.href='<?= $this->url(array('controller'=>'public','action'=>'profilobrands','nomeazienda' => 'Pampers','default',true));?>';" src="images/list brands/b12.png" width="100" height="100"></img></li>
   		<li><img title="clicca qui per vedere le loro offerte" onclick="window.location.href='<?= $this->url(array('controller'=>'public','action'=>'profilobrands','nomeazienda' => 'Zara','default',true));?>';" src="images/list brands/b13.png" width="100" height="100"></img></li>
   		<li><img title="clicca qui per vedere le loro offerte" onclick="window.location.href='<?= $this->url(array('controller'=>'public','action'=>'profilobrands','nomeazienda' => 'Gilette','default',true));?>';" src="images/list brands/b14.png" width="100" height="100"></img></li>
   		<li><img title="clicca qui per vedere le loro offerte" onclick="window.location.href='<?= $this->url(array('controller'=>'public','action'=>'profilobrands','nomeazienda' => 'Pepsi','default',true));?>';" src="images/list brands/b15.png" width="100" height="100"></img></li>
   		<li><img title="clicca qui per vedere le loro offerte" onclick="window.location.href='<?= $this->url(array('controller'=>'public','action'=>'profilobrands','nomeazienda' => 'Hm','default',true));?>';" src="images/list brands/b16.png" width="100" height="100"></img></li>
   		<li><img title="clicca qui per vedere le loro offerte" onclick="window.location.href='<?= $this->url(array('controller'=>'public','action'=>'profilobrands','nomeazienda' => 'LuisVuitton','default',true));?>';" src="images/list brands/b17.png" width="100" height="100"></img></li>
   		<li><img title="clicca qui per vedere le loro offerte" onclick="window.location.href='<?= $this->url(array('controller'=>'public','action'=>'profilobrands','nomeazienda' => 'Nike','default',true));?>';" src="images/list brands/b18.png" width="100" height="100"></img></li>
   		<li><img title="clicca qui per vedere le loro offerte" onclick="window.location.href='<?= $this->url(array('controller'=>'public','action'=>'profilobrands','nomeazienda' => 'Mcdonalds','default',true));?>';" src="images/list brands/b19.png" width="100" height="100"></img></li>
   		<li><img title="clicca qui per vedere le loro offerte" onclick="window.location.href='<?= $this->url(array('controller'=>'public','action'=>'profilobrands','nomeazienda' => 'Samsung','default',true));?>';" src="images/list brands/b20.png" width="100" height="100"></img></li>
                <li><img title="clicca qui per vedere le loro offerte" onclick="window.location.href='<?= $this->url(array('controller'=>'public','action'=>'profilobrands','nomeazienda' => 'Microsoft','default',true));?>';" src="images/list brands/b21.png" width="100" height="100"></img></li>
   		<li><img title="clicca qui per vedere le loro offerte" onclick="window.location.href='<?= $this->url(array('controller'=>'public','action'=>'profilobrands','nomeazienda' => 'CocaCola','default',true));?>';" src="images/list brands/b22.png" width="100" height="100"></img></li>
   		<li><img title="clicca qui per vedere le loro offerte" onclick="window.location.href='<?= $this->url(array('controller'=>'public','action'=>'profilobrands','nomeazienda' => 'Apple','default',true));?>';" src="images/list brands/b23.png" width="100" height="100"></img></li>
   		<li><img title="clicca qui per vedere le loro offerte" onclick="window.location.href='<?= $this->url(array('controller'=>'public','action'=>'profilobrands','nomeazienda' => 'Buweiser','default',true));?>';" src="images/list brands/b24.png" width="100" height="100"></img></li>
	</ul>
	<section class="pattern_img" id="pattern_img"></section>
  </section>
  
  
  <!-- sezione della presentazione delle categorie -->
  <section class="categories" id="categories">
  	<h1 class="title_messages">CATEGORIE</h1>
  	<h2 class="subtitle_messages">Tutti i coupon sono disponibili in diverse categorie in modo da facilitare l'accesso e la visibilitá</h2>	
  	<section class="one" id="one">
  		<br><br><br><br><br><br>
  		<p1 class="categories_message">TECNOLOGIA</p1>
  	</section>
  	<section class="two" id="two">
  		<br><br><br><br><br><br>
  		<p1 class="categories_message">UFFICIO E SERVIZI PROFESSIONALI</p1>
  	</section>
  	<section class="three" id="three">
  		<br><br><br><br><br><br>
  		<p1 class="categories_message">CIBI E BEVANDE</p1>
  	</section>
  	<section class="four" id="four">
  		<br><br><br><br><br><br>
  		<p1 class="categories_message">MODA E ABBIGLIAMENTO</p1>
  	</section>
  	<section class="five" id="five">
  		<br><br><br><br><br><br>
  		<p1 class="categories_message">TEMPO LIBERO, GIOCHI ED INTRATTENIMENTO</p1>
  	</section>
  	<section class="six" id="six">
  		<br><br><br><br><br><br>
  		<p1 class="categories_message">SPORT E FITNESS</p1>
  	</section>
  	<section class="seven" id="seven">
  		<br><br><br><br><br><br>
  		<p1 class="categories_message">CASA E GIARDINO</p1>
  	</section>
  	<section class="eight" id="eight">
  		<br><br><br><br><br><br>
  		<p1 class="categories_message">SALUTE E BELLEZZA</p1>
  	</section>
  	<section class="nine" id="nine">
  		<br><br><br><br><br><br>
  		<p1 class="categories_message">VIAGGI</p1>
  	</section>
  	<section class="ten" id="ten">
  		<br><br><br><br><br><br>
  		<p1 class="categories_message">AUTO E MOTO</p1>
  	</section>
  	<section class="eleven" id="eleven">
  		<br><br><br><br><br><br>
  		<p1 class="categories_message">ANIMALI</p1>
  	</section>
  </section>
  
  
  <!-- footer collocato a fine pagine-->
  <footer> 
  	<img src="images/LogoCWwhite.png" width="13%"></img>
  	<h3>© Copyright 2017 Coupon World SRL. All Rights Reserved. </h3>
  	<div>
  		<h3>Seguici su:</h3>
		<img id="fb" src="images/facebook.png" width="40" height="40"></img>
		<img src="images/instagram.png" width="40" height="40"></img>
		<img src="images/twitter.png" width="40" height="40"></img>
  	</div>
  </footer>
  
  
<!-- fine del contenitore principale della pagina -->
</div>
</body>
</html>
