<!-- sezione dedicata all'offerta selezionata-->
<div id="InformazioneOfferta">
  <h1>Informazioni sulla promozione del prodotto: <h3>NOMEPRODOTTO_SELEZIONATO</h3></h1>
  <img>FOTO_OFFERTA_SELEZIONATA</img>
  <br>
  <br>
  <h2>Nome prodotto: </h2><p>NOMEPRODOTTO_SELEZIONATO</p>
  <br>
  <h2>Categoria prodotto: </h2><p>CATEGORIAPRODOTTO_SELEZIONATO</p>
  <br>
  <h2>Brand prodotto:</h2><p>BRANDPRODOTTO_SELEZIONATO</p>
  <br>
  <h2>Descrizione del prodotto: </h2><p>DESCRIZIONEPRODOTTO_SELEZIONATO</p> 
  <br>
  <h2>Tipologia Offerta:</h2><p>TIPOLOGIAPRODOTTO_SELEZIONATO</p>
  <br>
  <h2>Modalità di fruizione</h2><p>MODALITADIFRUIZIONE_SELEZIONATO</p>
  <br>
  <h2>Località: </h2><p>LOCALITA_SELEZIONATO</p>
  <br>
  <h2>Validità: </h2>
  <h2>dal </h2><p>DATAINIZIO</p><h2> al </h2><p>DATAFINE</p>
</div>