<?php $this->headScript()
	->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js')
	->appendFile($this->baseUrl('js/functions.js'))
	->captureStart() ?>
            
// codice jQuery inserito da view-script nella sezione head della pagina
$(function()
{
     var actionUrl='<?= $this->url(array('controller' => 'public', 'action' => 'validalogin',), 'default'); ?>';
var formName='<?= $this->accediForm->getName() ?>';
$(":input").on('blur', function(event) {
var formElementId = $(this).attr('id');
doValidation(formElementId, actionUrl, formName);
});
});
    
<?php $this->headScript()->captureEnd() ?>
    
    
<div id="content">
    <div id="MyAccount">
        <h1>Bentornato in Coupon World!</h1>
        <h2>accedi con le tue credenziali e scopri le nuove offerte!</h2>
        <div id="FormAccedi">
            <!-- qui é presente la form Accedi -->
        <?php echo $this->accediForm ?> 
        </div>
    </div>
</div>