<input type="text" id="myInput" onkeyup="myFunctionTwo()" placeholder="Cerca per nome azienda..">
<div id="PaginaDeiBrands">
    <ul id="myUL">
        <?php foreach($this->paginadeibrands as $brands) :?>
            
        
        <li><a href="<?= $this->url(array('controller'=>'public','action'=>'paginadeibrands','idazienda' => $brands->idazienda,'default',true));?>"><?php echo $brands->nome?></a></li>
        
        <?php endforeach;?>
    </ul>
</div>


<!-- sezione dedicata al profilo del Brands selezionato -->
<div id="ProfiloBrandsDue">
  <?php if(!empty($this->brands)):?>
 

  <h1>Ecco le informazioni dell'azienda <?php echo '<h3>'. $this->brands['nome'].'</h3>'?></h1>
  <img><?php echo  $this->aziendaImg($this->brands['foto'],array('class' => 'immagineOfferta'));?></img>
  <br>
  <br>
  <h2>Nome: </h2><?php echo '<h7>'. $this->brands['nome'].'</h7>'?>
  <br>
  <h2>Settore: </h2><?php echo '<h7>'. $this->brands['settore'].'</h7>'?>
  <br>
  <h2>Descrizione: </h2><?php echo '<h7>'. $this->brands['descrizione'].'</h7>'?>
  <br>
  <h2>Indirizzo: </h2><?php echo '<h7>'. $this->brands['indirizzo'].'</h7>'?>
  <br>
  <h2>Cittá: </h2><?php echo '<h7>'. $this->brands['citta'].'</h7>'?>
  <br>
  <h2>Paese: </h2><?php echo '<h7>'. $this->brands['paese'].'</h7>'?>
  <br>
  <h2>Telefono: </h2><?php echo '<h7>'. $this->brands['telefono'].'</h7>'?>
  <br>

  <h2>Email: </h2><?php echo '<h7>'. $this->brands['email'].'</h7>'?>

  <br>
  <?php endif ?>
</div>
 <div id="offerteDeiBrands">
        <h1>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ❕ OFFERTE DELL'AZIENDA ❕</h1>
<?php if(!empty($this->offerte)): ?>
        
    <?php foreach ($this->offerte as $offerta) :?>
        <div id="offerta">
            <?php echo $this->offertaImg($offerta->immagine,array('class' => 'immagineOfferta'));?>
            <div id="infoOfferta"> 
                <?php echo '<h5>'. $offerta->nomeprodotto.'</h5>'?>                
                
                <br>
                    <?php echo '<h6>'. $offerta->tipo.'</h6>'?>
                <br>
                <a href="<?= $this->url(array('controller'=>'public','action'=>'profilobrands','nomeazienda' => $offerta->nome,'default',true));?>">
				<?php echo '<h9>'. $offerta->nome.'</h9>'?></a>
                    <br>
                                <?php echo '<h7>'. $offerta->nometipologia.'</h7>'?>
                    <br>
                                <?php echo '<h8>dal '.'<b>'.$offerta->datainizio.'</b> al <b>'.
                                        $offerta->datafine.'</b>'.'</h8>'?>
                                            
                                            
                    <button id="stampaofferta2" onClick="<?php 
                    
                 
                    
                    if($this->authInfo('role')=='user'){


                       $indirizzo = "window.location.href='".$this->url(array('controller'=>'user','action'=>'stampaofferta','offertaid' => $offerta->idpromozione ,'default',true))."'"; 

                      echo $indirizzo;
                    }
                    else
                        echo 'myFunction()';?>"></button>
                    
                    <div id="snackbar">Per accedere al codice coupon della promozione occorre registrarsi come utente!</div>
                    <a href="<?php echo $this->url(array('controller'=>'public','action'=>'informazioneofferta','offertaid' => $offerta->idpromozione ,'default',true));?>"><button id="visualizzaofferta2"></button></a>
            </div>
        </div>
        
        
        
                <?php endforeach ?>
        <div id="paginatorOfferteBrands">
                <?php if($this->offerte instanceof Zend_Paginator) {
	  		echo $this->paginationControl($this->offerte,'Sliding','public/paginator/_paginatorOffertaBrands.phtml');
                   } 
                 ?>
        </div>
        <?php endif ?>
    </div>
