<!-- sezione dedicata al profilo del Brands selezionato -->
<div id="ProfiloBrands">
  <h1>Benvenuto nel profilo dell'azienda <h3>AZIENDA_SELEZIONATA</h3></h1>
  <img>LOGO_AZIENDA_SELEZIONATA</img>
  <br>
  <br>
  <h2>Nome: </h2><p>NOME_AZIENDA_SELEZIONATA</p>
  <br>
  <h2>Ragione Sociale: </h2><p>RAGIONESOCIALE_AZIENDA_SELEZIONATA</p>
  <br>
  <h2>Settore: </h2><p>SETTORE_AZIENDA_SELEZIONATA</p>
  <br>
  <h2>Descrizione: </h2><p>DESCRIZIONE_AZIENDA_SELEZIONATA</p>
  <br>
  <h2>Indirizzo: </h2><p>INDIRIZZO_AZIENDA_SELEZIONATA</p>
  <br>
  <h2>Cittá: </h2><p>CITTA_AZIENDA_SELEZIONATA</p>
  <br>
  <h2>Paese: </h2><p>PAESE_AZIENDA_SELEZIONATA</p>
  <br>
  <h2>Telefono: </h2><p>TELEFONO_AZIENDA_SELEZIONATA</p>
  <br>
  <h2>Fax: </h2><p>FAX_AZIENDA_SELEZIONATA</p>
  <br>
  <h2>Email: </h2><p>EMAIL_AZIENDA_SELEZIONATA</p>
  <br>
</div>
