<!-- sezione dedicata al profilo del Brands selezionato -->
<div id="ProfiloBrands">
  <?php foreach($this->infoazienda as $azienda) :?>
  <?php endforeach ?>
  <h1>Benvenuto nel profilo dell'azienda <?php echo '<h3>'. $azienda->nome.'</h3>'?></h1>
  <img><?php echo  $this->offertaImg($azienda->foto,array('class' => 'immagineOfferta'));?></img>
  <br>
  <br>
  <h2>Nome: </h2><?php echo '<h7>'. $azienda->nome.'</h7>'?>
  <br>
  <h2>Settore: </h2><?php echo '<h7>'. $azienda->settore.'</h7>'?>
  <br>
  <h2>Descrizione: </h2><?php echo '<h7>'. $azienda->descrizione.'</h7>'?>
  <br>
  <h2>Indirizzo: </h2><?php echo '<h7>'. $azienda->indirizzo.'</h7>'?>
  <br>
  <h2>Cittá: </h2><?php echo '<h7>'. $azienda->citta.'</h7>'?>
  <br>
  <h2>Paese: </h2><?php echo '<h7>'. $azienda->paese.'</h7>'?>
  <br>
  <h2>Telefono: </h2><?php echo '<h7>'. $azienda->telefono.'</h7>'?>
  <br>

  <h2>Email: </h2><?php echo '<h7>'. $azienda->email.'</h7>'?>

  <br>
</div>
