<div id="content">	
	<!-- SUBHEADER CONTENTENTE INFORMAZIONIA AGGIUNTIVE AL SITO -->
	<div id="subheader">
		&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
		<a ><img src="<?php echo $this->baseURL();?>/images/icons/h24.png" class="icons"></img><h4>offerte aggiornate 24 ore su 24 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</h4></a>
		<a ><img src="<?php echo $this->baseURL();?>/images/icons/brands.png" class="icons"></img><h4>i migliori brands a portata di click &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</h4></a>
		<a ><img src="<?php echo $this->baseURL();?>/images/icons/risparmio.png" class="icons"></img><h4>risparmio garantito &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</h4></a>
		<a href="<?= $this->url(array('controller'=>'public','action'=>'viewstatic','staticPage' => 'faq','default',true));?>"><img src="<?php echo $this->baseURL();?>/images/icons/FAQ.png" class="icons"></img><h4>dubbi? FAQ semplice e intuitiva!</h4></a>
	</div>	
	<div id="navMenu">
            <ul id="categorie">
            <h1>&nbsp; &nbsp; ≡ CATEGORIE</h1>
            <!-- lista delle categorie dei prodotti presenti nel sito -->
            <?php foreach ($this->tipologie as $tipologia) :?>
                <li><a href="<?= $this->url(array('controller'=>'public','action'=>'categorie','catId'=>$tipologia->nometipologia,'default',true));?>">&nbsp; &nbsp;<?php echo $tipologia->nometipologia ?></a></li>
            <?php endforeach;?>
            </ul>
	</div>
        
        <!--Sezione dinamica che in base al click sulla categoria apre la pagina della categoria giusta --> 
        <?php  if(!empty($this->offertaRicercata)) :?>
            <?php echo '<h1 class="titolocategoria">Risultati trovati per '.$this->nomeDaCercare.'</h1>';?>
        <?php endif ?>
     
        <?php foreach ($this->offertaRicercata as $offertaRicercata) :?>
		<div id="offertaCategoria">
                     <?php echo $this->offertaImg($offertaRicercata->immagine,array('class' => 'immagineOfferta'));?>
			<div id="infoOfferta"> 
                               
                                <?php echo '<h5>Nome Prodotto: '. $offertaRicercata->nomeprodotto.'</h5>'?>
                                <br>
				<?php echo '<h6>Categoria: '. $offertaRicercata->nometipologia.'</h6>'?>
				<br>
				<?php echo '<h7>Azienda: '. $offertaRicercata->tipo.'</h7>'?>
				<br>
       <a href="<?= $this->url(array('controller'=>'public','action'=>'profilobrands','nomeazienda' => $offertaRicercata->nome,'default',true));?>">
                 	<?php echo '<h8>Offerta: '. $offertaRicercata->nome.'</h8>'?>
				<br>
                                <?php echo '<h8>dal '.'<b>'.$offertaRicercata->datainizio.'</b> al <b>'.
                                        $offertaRicercata->datafine.'</b>'.'</h8>'?>
				<button id="stampaofferta"></button>
			</div>
		</div>
                <?php endforeach ?>
          <?php if($this->offertaRicercata instanceof Zend_Paginator) {
                echo $this->paginationControl($this->offertaRicercata,'Sliding','public/_paginatorRicerca.phtml');
	  } 
	  ?>
        
        <?php if(empty($this->offertaRicercata)) :?>
            <?php echo '<h1 class="titolocategoria">Nessun Risultato trovato</h1>';?>
        <?php endif ?>
      
 
   
</div>
