<div id="content">	
	<!-- SUBHEADER CONTENTENTE INFORMAZIONIA AGGIUNTIVE AL SITO -->
	<div id="subheader">
		&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
		<a href=""><img src="<?php echo $this->baseURL();?>/images/icons/h24.png" class="icons"></img><h4>offerte aggiornate 24 ore su 24 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</h4></a>
		<a href=""><img src="<?php echo $this->baseURL();?>/images/icons/brands.png" class="icons"></img><h4>i migliori brands a portata di click &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</h4></a>
		<a href=""><img src="<?php echo $this->baseURL();?>/images/icons/risparmio.png" class="icons"></img><h4>risparmio garantito &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</h4></a>
		<a href="<?= $this->url(array('controller'=>'public','action'=>'viewstatic','staticPage' => 'faq','default',true));?>"><img src="<?php echo $this->baseURL();?>/images/icons/FAQ.png" class="icons"></img><h4>dubbi? FAQ semplice e intuitiva!</h4></a>
	</div>	
	<div id="navMenu">
            <ul id="categorie">
            <h1>&nbsp; &nbsp; ≡ CATEGORIE</h1>
            <!-- lista delle categorie dei prodotti presenti nel sito -->
            <li><a href="<?= $this->url(array('controller'=>'public','action'=>'categorie','catId'=>'tecnologia','default',true));?>">&nbsp; &nbsp; Tecnologia</a></li>
            <li><a href="<?= $this->url(array('controller'=>'public','action'=>'categorie','catId'=>'ufficioeservizi','default',true));?>">&nbsp; &nbsp; Ufficio e servizi</a></li>
            <li><a href="<?= $this->url(array('controller'=>'public','action'=>'categorie','catId'=>'modaeabbigliamento','default',true));?>">&nbsp; &nbsp; Moda e abbigliamento</a></li>
            <li><a href="<?= $this->url(array('controller'=>'public','action'=>'categorie','catId'=>'cibiebevande','default',true));?>">&nbsp; &nbsp; Cibi e bevande</a></li>
            <li><a href="<?= $this->url(array('controller'=>'public','action'=>'categorie','catId'=>'giochiedintrattenimento','default',true));?>">&nbsp; &nbsp; Giochi ed intrattenimento</a></li>
            <li><a href="<?= $this->url(array('controller'=>'public','action'=>'categorie','catId'=>'sportefitness','default',true));?>">&nbsp; &nbsp; Sport e fitness</a></li>
            <li><a href="<?= $this->url(array('controller'=>'public','action'=>'categorie','catId'=>'casaegiardino','default',true));?>">&nbsp; &nbsp; Casa e giardino</a></li>
            <li><a href="<?= $this->url(array('controller'=>'public','action'=>'categorie','catId'=>'saluteebellezza','default',true));?>">&nbsp; &nbsp; Salute e bellezza</a></li>
            <li><a href="<?= $this->url(array('controller'=>'public','action'=>'categorie','catId'=>'viaggi','default',true));?>">&nbsp; &nbsp; Viaggi</a></li>
            <li><a href="<?= $this->url(array('controller'=>'public','action'=>'categorie','catId'=>'autoemoto','default',true));?>">&nbsp; &nbsp; Auto e moto</a></li>
            <li><a href="<?= $this->url(array('controller'=>'public','action'=>'categorie','catId'=>'animali','default',true));?>">&nbsp; &nbsp; Animali</a></li>
            </ul>
	</div>
        
        <!--Sezione dinamica che in base al click sulla categoria apre la pagina della categoria giusta --> 
        <?php  if($this->flag) :?>
            <?php echo '<h1 class="titolocategoria">Risultati trovati per '.$this->nomeDaCercare.'</h1>';?>
  
        ?>
        <?php foreach ($this->offertaRicercata as $offertaRicercata) :?>
		<div id="offertaCategoria">
                     <?php echo $this->offertaImg($offertaRicercata->immagine,array('class' => 'immagineOfferta'));?>
			<div id="infoOfferta"> 
                               
                                <?php echo '<h5>'. $offertaRicercata->nomeprodotto.'</h5>'?>
                                <br>
				<?php echo '<h6>'. $offertaRicercata->categoria.'</h6>'?>
				<br>
				<?php echo '<h7>'. $offertaRicercata->azienda_idazienda.'</h7>'?>
				<br>
				<?php echo '<h8>'. $offertaRicercata->tipologia.'</h8>'?>
				<br>
                                <?php echo '<h8>dal '.'<b>'.$offertaRicercata->datainizio.'</b> al <b>'.
                                        $offertaRicercata->datafine.'</b>'.'</h8>'?>
				<button id="stampaofferta"></button>
			</div>
		</div>
                <?php endforeach ?>
          <?php if($this->offertaRicercata instanceof Zend_Paginator) {
                echo $this->paginationControl($this->offertaRicercata,'Sliding','public/_paginatorRicerca.phtml');
	  } 
	  ?>
        <?php endif ?>
        <?php if(!$this->flag) :?>
            <?php echo '<h1 class="titolocategoria">Nessun Risultato trovato</h1>';?>
        <?php endif ?>
      
    
        <!-- lista delle tipologie delle offerte presenti nel sito -->
            <div id="listaTipologie">
                <h1>&nbsp; &nbsp; ≡ TIPOLOGIE</h1>
                    <form action="">
                        <fieldset>
                            <input type="checkbox" name="Percentuale" value="Percentuale"/> Percentuale
                            <br/> 
                            <input type="checkbox" name="Combo" value="Combo"/> Combo
                            <br/>
                            <input type="checkbox" name="Altro" value="Altro"/> Altro 
                            <button id="bottoneConferma">CONFERMA</button>
                        </fieldset>
                    </form>
            </div>
 
       
        
	<div id="campoCercaAzienda">
		<h2>&nbsp; &nbsp;BRANDS</h2>
		<input type="text" name="search" placeholder="Cerca l'offerta per azienda">
		<button></button>
	</div>	
</div>
