<div id="navMenuAdmin">
    <h1>&nbsp; &nbsp; ≡ AMMINISTRATORE</h1>
    <li class="menu"> <!-- costituisce ogni sezione del menu principale -->
        <ul>
            <!-- titolo della sezione che fa aprire il sotto menu -->
            <li class="title"><a href="#">&nbsp; &nbsp; gestione aziende</a></li>
            <li class="sub-menu">
                <ul>
                    <li><a href="<?= $this->url(array('controller'=>'admin','action'=>'nuovaazienda','default',true));?>">inserisci nuova azienda</a></li> 
                    <li>modifica azienda</li>
                    <li>elimina azienda</li>
                </ul>
            </li>
        </ul> 
    </li> 
    <li class="menu"> <!-- costituisce ogni sezione del menu principale -->
        <ul>
            <!-- titolo della sezione che fa aprire il sotto menu -->
            <li class="title"><a href="#">&nbsp; &nbsp; gestione utenti</a></li>
            <li class="sub-menu">
                <ul>
                    <li>modifica utente</li> 
                    <li>cancella utente</li>
                </ul>
            </li>
        </ul> 
    </li>
     <li class="menu"> <!-- costituisce ogni sezione del menu principale -->
        <ul>
            <!-- titolo della sezione che fa aprire il sotto menu -->
            <li class="title"><a href="#">&nbsp; &nbsp; gestione staff</a></li>
            <li class="sub-menu">
                <ul>
                    <li>inserisci nuovo staff</li> 
                    <li>modifica staff</li> 
                    <li>cancella staff</li>
                </ul>
            </li>
        </ul> 
    </li>
    <li class="menu"> <!-- costituisce ogni sezione del menu principale -->
        <ul>
            <!-- titolo della sezione che fa aprire il sotto menu -->
            <li class="title"><a href="#">&nbsp; &nbsp; gestione tipologie</a></li>
            <li class="sub-menu">
                <ul>
                    <li><a href="<?= $this->url(array('controller'=>'admin','action'=>'nuovatipologia','default',true));?>">inserisci nuova tipologia</a></li> 
                    <li>modifica tipologia</li>
                    <li>elimina tipologia</li>
                </ul>
            </li>
        </ul> 
    </li>
    <li class="menu"> <!-- costituisce ogni sezione del menu principale -->
        <ul>
            <!-- titolo della sezione che fa aprire il sotto menu -->
            <li class="title"><a href="#">&nbsp; &nbsp; gestione FAQ</a></li>
            <li class="sub-menu">
                <ul>
                    <li>inserisci nuova domanda e nuova risposta</li> 
                    <li>modifica domanda e risposta</li>
                    <li>elimina domanda e risposta</li>
                </ul>
            </li>
        </ul> 
    </li>
    <li class="menu"> <!-- costituisce ogni sezione del menu principale -->
        <ul>
            <!-- titolo della sezione che fa aprire il sotto menu -->
            <li class="title"><a href="#">&nbsp; &nbsp; statistiche del sito</a></li>
            <li class="sub-menu">
                <ul>
                    <li>numero totale coupon emessi</li> 
                    <li>numero coupon emessi per quella promozione selezionato</li>
                    <li>numero coupon emessi per utente selezionato</li>
                </ul>
            </li>
        </ul> 
    </li>
</div>

