<div id="content">
    <div id="ModificaEliminaTipologia">
        <h2>qui puoi modificare o eliminare una tipologia.</h2>
        <table>
            <caption>
                <p>Qui di sotto tutte le tipologie in Coupon World</p>
            </caption>
            <thead>
                <tr>
                    <th>Nome Tipologia</th><th>Descrizione</th>
                </tr>
              </thead>
            <?php foreach($this->tipologie as $tipologia): ?>
                <tr class='border_bottom'>
                    <td><?php echo $tipologia->nometipologia;?></td>
                    <td><?php echo $tipologia->descrizionetipologia;?></td>
                    <td><button 
                    onClick="window.location.href='<?=
                    $this->url(array('controller'=>'admin','action'=>'modificatipologiapage','idtipologia'=>$tipologia->idtipologia,'default',true));
                    ?>';"
                            >Modifica</button></td>
                    <td><td><button 
                    onClick="window.location.href='<?=
                    $this->url(array('controller'=>'admin','action'=>'eliminatipologia','idtipologia'=>$tipologia->idtipologia,'default',true));
                    ?>';">Elimina</button></td>
                    <br>
                </tr>
                <?php endforeach ?>
            </tbody>
        </table>
         <?php if($this->tipologie instanceof Zend_Paginator) {
                echo $this->paginationControl($this->tipologie,'Sliding','admin/paginator/_paginatormodificatipologia.phtml');
	  } 
	  ?>
    </div>
</div>