<div id="content">
    <div id="ModificaEliminaAzienda">
        <h2>qui puoi modificare o eliminare un' azienda.</h2>
        <table>
            <caption>
                <p>Qui di sotto tutte le aziende in Coupon World</p>
            </caption>
            <thead>
                <tr>
                    <th>Nome Azienda</th><th>Ragione Sociale</th><th>Settore</th><th>Partita IVA</th>
                    <th>Descrizione</th><th>Indirizzo</th><th>Città</th><th>Paese</th><th>Telefono</th>
                    <th>Mail Azienda</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($this->aziende as $azienda): ?>
                <tr class='border_bottom'>
                    <td><?php echo $azienda->nome;?></td>
                    <td><?php echo $azienda->ragionesociale;?></td>
                    <td><?php echo $azienda->settore;?></td>
                    <td><?php echo $azienda->partitaiva;?></td>
                    <td><?php echo $azienda->descrizione;?></td>
                    <td><?php echo $azienda->indirizzo;?></td>
                    <td><?php echo $azienda->citta;?></td>
                    <td><?php echo $azienda->paese;?></td>
                    <td><?php echo $azienda->telefono;?></td>
                    <td><?php echo $azienda->email;?></td>
                    <td><button 
                    onClick="window.location.href='<?=
                    $this->url(array('controller'=>'admin','action'=>'modificaaziendapage','idazienda'=>$azienda->idazienda,'default',true));
                    ?>';"
                            >Modifica</button></td>
                    <td>
                    <button 
                    onClick="window.location.href='<?=
                    $this->url(array('controller'=>'admin','action'=>'eliminaazienda','idazienda'=>$azienda->idazienda,'default',true));
                    ?>';">Elimina</button></td></td>
                    <br>
                </tr>
                <?php endforeach ?>
            </tbody>
        </table>
         <?php if($this->aziende instanceof Zend_Paginator) {
                echo $this->paginationControl($this->aziende,'Sliding','admin/paginator/_paginatormodificaazienda.phtml');
	  } 
	  ?>
    </div>
</div>
