<div id="navMenuAdmin">
    <h1>&nbsp; &nbsp; ≡ AMMINISTRATORE</h1>
    <li class="menu"> <!-- costituisce ogni sezione del menu principale -->
        <ul>
            <!-- titolo della sezione che fa aprire il sotto menu -->
            <li class="title"><a href="#">&nbsp; &nbsp; gestione aziende</a></li>
            <li class="sub-menu">
                <ul>
                    <li><a href="<?= $this->url(array('controller'=>'admin','action'=>'nuovaazienda','default',true));?>">inserisci nuova azienda</a></li> 
                    <li><a href="<?= $this->url(array('controller'=>'admin','action'=>'modificaeliminaazienda','default',true));?>">modifica/elimina azienda</a></li>                   
                </ul>
            </li>
        </ul> 
    </li> 
    <li class="menu"> <!-- costituisce ogni sezione del menu principale -->
        <ul>
            <!-- titolo della sezione che fa aprire il sotto menu -->
            <li class="title"><a href="#">&nbsp; &nbsp; gestione utenti</a></li>
            <li class="sub-menu">
                <ul>
                    <li><a href="<?= $this->url(array('controller'=>'admin','action'=>'modificaeliminautente','default',true));?>">modifica/elimina utente</a></li> 
                </ul>
            </li>
        </ul> 
    </li>
     <li class="menu"> <!-- costituisce ogni sezione del menu principale -->
        <ul>
            <!-- titolo della sezione che fa aprire il sotto menu -->
            <li class="title"><a href="#">&nbsp; &nbsp; gestione staff</a></li>
            <li class="sub-menu">
                <ul>
                    <li><li><a href="<?= $this->url(array('controller'=>'admin','action'=>'nuovostaff','default',true));?>">inserisci nuovo staff</a></li> 
                    <li><a href="<?= $this->url(array('controller'=>'admin','action'=>'modificaeliminastaff','default',true));?>">modifica/elimina staff</a></li>  
                </ul>
            </li>
        </ul> 
    </li>
    <li class="menu"> <!-- costituisce ogni sezione del menu principale -->
        <ul>
            <!-- titolo della sezione che fa aprire il sotto menu -->
            <li class="title"><a href="#">&nbsp; &nbsp; gestione tipologie</a></li>
            <li class="sub-menu">
                <ul>
                    <li><a href="<?= $this->url(array('controller'=>'admin','action'=>'nuovatipologia','default',true));?>">inserisci nuova tipologia</a></li> 
                    <li><a href="<?= $this->url(array('controller'=>'admin','action'=>'modificaeliminatipologia','default',true));?>">modifica/elimina tipologia</a></li> 
                </ul>
            </li>
        </ul> 
    </li>
    <li class="menu"> <!-- costituisce ogni sezione del menu principale -->
        <ul>
            <!-- titolo della sezione che fa aprire il sotto menu -->
            <li class="title"><a href="#">&nbsp; &nbsp; gestione FAQ</a></li>
            <li class="sub-menu">
                <ul>
                    <li><a href="<?= $this->url(array('controller'=>'admin','action'=>'nuovadomandarisposta','default',true));?>">inserisci nuova domanda e nuova risposta</a></li> 
                    <li><a href="<?= $this->url(array('controller'=>'admin','action'=>'modificaeliminadomandarisposta','default',true));?>">modifica/elimina domanda e risposta</a></li> 
                </ul>
            </li>
        </ul> 
    </li>
    <li class="menu"> <!-- costituisce ogni sezione del menu principale -->
        <ul>
            <!-- titolo della sezione che fa aprire il sotto menu -->
            <li class="title"><a href="#">&nbsp; &nbsp; statistiche del sito</a></li>
            <li class="sub-menu">
                <ul>
                    <li>numero totale coupon emessi</li> 
                    <li>numero coupon emessi per quella promozione selezionato</li>
                    <li>numero coupon emessi per utente selezionato</li>
                </ul>
            </li>
        </ul> 
    </li>
</div>

<div id="content">
    <div id="ModificaEliminaAzienda">
        <h2>qui puoi modificare o eliminare un' azienda.</h2>
        <table>
            <caption>
                <p>Qui di sotto tutte le aziende in Coupon World</p>
            </caption>
            <thead>
                <tr>
                    <th>Nome Azienda</th><th>Ragione Sociale</th><th>Settore</th><th>Partita IVA</th>
                    <th>Descrizione</th><th>Indirizzo</th><th>Città</th><th>Paese</th><th>Telefono</th>
                    <th>Mail Azienda</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($this->aziende as $azienda): ?>
                <tr class='border_bottom'>
                    <td><?php echo $azienda->nome;?></td>
                    <td><?php echo $azienda->ragionesociale;?></td>
                    <td><?php echo $azienda->settore;?></td>
                    <td><?php echo $azienda->partitaiva;?></td>
                    <td><?php echo $azienda->descrizione;?></td>
                    <td><?php echo $azienda->indirizzo;?></td>
                    <td><?php echo $azienda->citta;?></td>
                    <td><?php echo $azienda->paese;?></td>
                    <td><?php echo $azienda->telefono;?></td>
                    <td><?php echo $azienda->email;?></td>
                    <td><button>Modifica</button></td><td><button>Elimina</button></td>
                    <br>
                </tr>
                <?php endforeach ?>
            </tbody>
        </table>
         <?php if($this->aziende instanceof Zend_Paginator) {
                echo $this->paginationControl($this->aziende,'Sliding','admin/paginator/_paginatormodificaazienda.phtml');
	  } 
	  ?>
    </div>
</div>
