<div id="content">
    <div id="ModificaEliminaDomandaRisposta">
        <h2>qui puoi modificare o eliminare una domanda con la relativa risposta.</h2>
        <table>
            <caption>
                <p>Qui di sotto tutte le domande e risposte della FAQ di Coupon World</p>
            </caption>
            <thead>
                <tr>
                    <th>Domanda</th><th>Risposta</th>
                </tr>
            </thead>
            <?php foreach($this->faq as $faq): ?>
                <tr class='border_bottom'>
                    <td><?php echo $faq->domanda;?></td>
                    <td><?php echo $faq->risposta;?></td>
                    <td><button 
                    onClick="window.location.href='<?=
                    $this->url(array('controller'=>'admin','action'=>'modificafaqpage','idfaq'=>$faq->idfaq,'default',true));
                    ?>';"
                            >Modifica</button></td>
                    <td><td><button 
                    onClick="window.location.href='<?=
                    $this->url(array('controller'=>'admin','action'=>'eliminafaq','idfaq'=>$faq->idfaq,'default',true));
                    ?>';">Elimina</button></td>
                    <br>
                </tr>
                <?php endforeach ?>
            </tbody>
        </table>
         <?php if($this->faq instanceof Zend_Paginator) {
                echo $this->paginationControl($this->faq,'Sliding','admin/paginator/_paginatormodificafaq.phtml');
	  } 
	  ?>
    </div>
</div>