<ul id="categorie">
           <h1>&nbsp; &nbsp; ≡ CATEGORIE</h1>
            <!-- lista delle categorie dei coupon presenti nel sito -->
            <li>&nbsp; &nbsp;
                <a href="<?= $this->url(array('controller'=>'public'
                    'action'=>'index'))">
                

               Tecnologia</li>
            <li>&nbsp; &nbsp; Ufficio e servizi</li>
            <li>&nbsp; &nbsp; Moda e abbigliamento</li>
            <li>&nbsp; &nbsp; Cibi e bevande</li>
            <li>&nbsp; &nbsp; Giochi ed intrattenimento</li>
            <li>&nbsp; &nbsp; Sport e fitness</li>
            <li>&nbsp; &nbsp; Casa e giardino</li>
            <li>&nbsp; &nbsp; Salute e bellezza</li>
            <li>&nbsp; &nbsp; Viaggi</li>
            <li>&nbsp; &nbsp; Auto e moto</li>
            <li>&nbsp; &nbsp; Animali</li>
</ul>
