<!doctype html>
<html lang="it-IT">
<head>
	<meta charset="utf-8">
	<!-- compatibilitá per browser come Internet Explorer -->
	<meta http-equiv="X-UA-Compatible" content="IE=edge"> 
	<!-- fa sì che il sito web venga visualizzato a tutto schermo, senza ridimensionare nulla --> 
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Homepage</title>
	<link rel="stylesheet" href="css/layout.css">
		
</head>
<body>
	<!-- UPHEADER CONTENTENTE MENU -->
	<div id="upheader">
	</div>
	<!-- HEADER CONTENTENTE BARRA DI RICERCA E BOTTONE -->
	<div id="header">
            <img id="logo" src="images/LogoCWwhite.png"></img>
	</div>
	<!-- SUBHEADER CONTENTENTE INFORMAZIONIA AGGIUNTIVE AL SITO -->
	<div id="subheader"></div>
	<div id="navMenu">
	
	</div>
	<!-- Sezione che contiene lo slideshow e i promotion banner (che diventa poi dinamica al click sulle categorie) -->
<div id="mainContent">
		<!-- SLIDESHOW CHE CONTIENE I BANNER DELLE CATEGORIE -->
	</div>
	<footer id="footer">
		<div id="footersx">
			<img src="images/LogoCWwhite.png" height="30%" width="30%">
			<br>
			<footertext>© Copyright 2017 Coupon World SRL. All Rights Reserved</footertext>
			<br>
			<footertext>trova tutti gli ultimi coupon stampabili e offerte speciali online </footertext>
			<br>
			<footertext>seguici su: </footertext>
			<br>
			<img class="footericon" src="images/icons/facebook.png" width="30px" height="30px">
			<img class="footericon" src="images/icons/instagram.png" width="30px" height="30px">
			<img class="footericon" src="images/icons/twitter.png" width="30px" height="30px">
		</div>
		<div id="footerdx">
			<footertext><b>Chi siamo</b>&nbsp; &nbsp; &nbsp; &nbsp;Piattaforma che offre i coupon da Aprile 2017</footertext>
			<br>
			<footertext><b>Dove siamo</b>&nbsp; &nbsp;Via Brecce Bianche, 32, Ancona, IT</footertext>
			<br>
			<footertext><b>Contatti</b>&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;07 345 678</footertext>
			<br>
			<footertext><b>Email</b>&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;staff@couponworld.it</footertext>
		</div>
	</footer>
</body>
</html>