<!-- Sezione FAQ: Frequently Asked Question -->
<div id="FAQsection">
    <h1>Benvenuto nella sezione FAQ di Coupon World</h1>
    <h2>qui potrai trovare tutte le informazioni utili per la vostra assistenza nella navigazione</h2>
    <br>
    <h3>Come posso accedere alle offerte?</h3>
    <h4>Coupon World é una piattaforma free-access e per tal ragione é possibile accedere e visionare le offerte 
        semplicemente navigando sul nostro sito. Tuttavia il codice promozionale del coupon é accessibile solo se 
        si é registrati al nostro portale.</h4>
    <br>
    <h3>Come posso registrarmi alla piattaforma?</h3>
    <h4>per accedere ai coupon occorre registrarsi, cliccando nella homepage la voce: "Registrazione"</h4>
    <br>
    <h3>Come posso cercare i prodotti?</h3>
    <h4>per cercare prodotti nel nostro portale basta andare nella homepage e cercare nella barra di ricerca in 
        alto a destra</h4>
    <br>
    <h3>Come posso filtrare i prodotti per restringere i risultati?</h3>
    <h4>Si, é possibile filtrare le offerte selezionando una categoria di partenza e, successivamente, spuntando 
        una delle voci presenti nel checkbox "TIPOLOGIE" sulla sinistra.</h4>
    <br>
    <h3>Come posso comunicarvi eventuali problemi sulla piattaforma?</h3>
    <h4>É possibile comunicare con Coupon World attraverso le varie informazioni presenti in qualsiasi pagina del dominio. 
        Potete scriverci una mail, chiamare il nostro telefono o venirci a trovare in sede</h4>
    
    <h2>Lo staff di Coupon World</h2>
</div>
