
<div id="content">
    <div id="ModificaEliminaPromozione">
     <h2>qui puoi modificare o eliminare una promozione.</h2>
        <table>
            <caption>
                <p>Lista delle promozioni</p>
            </caption>
            <thead>
                <tr>
                    <th>Nome Prodotto</th><th>Data Fine</th><th>Descrizione</th>
                    <th>Luogo Fruizione</th><th>Modalità</th><th>Tipo Offerta</th><th>Nome Azienda</th>
                    <th>Tipologia</th>
                </tr>
            </thead>
            <?php foreach($this->promozione as $promozione): ?>
            <tr class='border_bottom'>
                <td><?php echo $promozione->nomeprodotto;?></td>
                <td><?php echo $promozione->datafine;?></td>
                <td><?php echo $promozione->descrizione;?></td>
                <td><?php echo $promozione->localita;?></td>
                <td><?php echo $promozione->modalita;?></td>
                <td><?php echo $promozione->tipo;?></td>
                <td><?php echo $promozione->nome;?></td>
                <td><?php echo $promozione->nometipologia?></td>
                 <td><button 
                    onClick="window.location.href='<?=
                    $this->url(array('controller'=>'staff','action'=>'modificapromozionepage','idpromo'=>$promozione->idpromozione,'default',true));
                    ?>';"
                            >Modifica</button></td>
                    <td>
                <td><button 
                    onClick="window.location.href='<?=
                    $this->url(array('controller'=>'staff','action'=>'eliminapromozione','idpromo'=>$promozione->idpromozione,'default',true));
                    ?>';">Elimina</button></td>
            <br>
            </tr>
                <?php endforeach ?>
            </tbody>
        </table>
         <?php if($this->promozione  instanceof Zend_Paginator) {
                echo $this->paginationControl($this->promozione,'Sliding','staff/paginator/_paginatormodificapromozione.phtml');
	  } 
	  ?>
    </div>
</div>
