
<!-- 
    Spazio dedicato alla Form di modifica dei dettagli dello staff 
    ovvero la modificata di dati di una form popolata tramite collegamento
    al database
-->
<div id="content">
     <div id="ModificaProfiloStaff">
        <h2>qui puoi modificare il tuo profilo.</h2>
        <div class="Forms">
            <!-- qui é presente la form Modifica Profilo -->
            
        </div>
    </div>
</div>